import type { Product } from "@/lib/types";

// Dummy data for the home page until products are wired in from Supabase.
export const PLACEHOLDER_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Noir Heeled Sandal",
    description: "Strappy champagne-gold heeled sandal.",
    price: 32000,
    original_price: 45000,
    category: "footwear",
    sizes: ["38", "39", "40", "41"],
    image_url: "",
    gallery: null,
    in_stock: true,
    featured: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "2",
    name: "Champagne Tote Bag",
    description: "Structured tote in soft blush leather.",
    price: 28000,
    original_price: null,
    category: "bags",
    sizes: null,
    image_url: "",
    gallery: null,
    in_stock: true,
    featured: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "3",
    name: "Gold Link Necklace",
    description: "Delicate layered gold-plated necklace.",
    price: 15000,
    original_price: 21000,
    category: "accessories",
    sizes: null,
    image_url: "",
    gallery: null,
    in_stock: true,
    featured: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "4",
    name: "Ivory Pointed Pump",
    description: "Classic pointed-toe pump in ivory satin.",
    price: 34000,
    original_price: null,
    category: "footwear",
    sizes: ["37", "38", "39", "40"],
    image_url: "",
    gallery: null,
    in_stock: true,
    featured: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "5",
    name: "Blush Clutch",
    description: "Mini clutch with gold chain strap.",
    price: 19500,
    original_price: 26000,
    category: "bags",
    sizes: null,
    image_url: "",
    gallery: null,
    in_stock: true,
    featured: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
];
